### ISSUE TITLE
Wrong Model Mentioned

### ISSUE THREAD

**Issue by ecyht2** [mmwillet/TTS.cpp#5]
I noticed in README.md and py-gguf README, the model https://huggingface.co/ylacombe/parler_tts_mini_v0.1 is mentioned but in the actual conversion script I saw https://huggingface.co/parler-tts/parler-tts-mini-v1 is used instead. Is the linked model incorrect and needs updating?

**Comment by mmwillet** [comment]
Looks like there are still some mentions of the original model. Just updated.
